package bean;
// Generated 13/12/2024 19:27:56 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompraFornecedorIar generated by hbm2java
 */
@Entity
@Table(name="compra_fornecedor_iar"
    ,catalog="db_zahraa_tormos"
)
public class CompraFornecedorIar  implements java.io.Serializable {


     private CompraFornecedorIarId id;
     private CompraIar compraIar;
     private FornecedorZht fornecedorZht;
     private byte quantidadeIar;

    public CompraFornecedorIar() {
    }

    public CompraFornecedorIar(CompraFornecedorIarId id, CompraIar compraIar, FornecedorZht fornecedorZht, byte quantidadeIar) {
       this.id = id;
       this.compraIar = compraIar;
       this.fornecedorZht = fornecedorZht;
       this.quantidadeIar = quantidadeIar;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkCompraIar", column=@Column(name="fk_compra_iar", nullable=false) ), 
        @AttributeOverride(name="fkFornecedorIar", column=@Column(name="fk_fornecedor_iar", nullable=false) ) } )
    public CompraFornecedorIarId getId() {
        return this.id;
    }
    
    public void setId(CompraFornecedorIarId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_compra_iar", nullable=false, insertable=false, updatable=false)
    public CompraIar getCompraIar() {
        return this.compraIar;
    }
    
    public void setCompraIar(CompraIar compraIar) {
        this.compraIar = compraIar;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_fornecedor_iar", nullable=false, insertable=false, updatable=false)
    public FornecedorZht getFornecedorZht() {
        return this.fornecedorZht;
    }
    
    public void setFornecedorZht(FornecedorZht fornecedorZht) {
        this.fornecedorZht = fornecedorZht;
    }

    
    @Column(name="quantidade_iar", nullable=false)
    public byte getQuantidadeIar() {
        return this.quantidadeIar;
    }
    
    public void setQuantidadeIar(byte quantidadeIar) {
        this.quantidadeIar = quantidadeIar;
    }




}


