package bean;
// Generated 06/02/2025 17:20:47 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompraIar generated by hbm2java
 */
@Entity
@Table(name="compra_iar"
    ,catalog="db_zahraa_tormos"
)
public class CompraIar  implements java.io.Serializable {


     private int idCompraIar;
     private FornecedorZht fornecedorZht;
     private FuncionarioIar funcionarioIar;
     private Date dataIar;
     private double valorIar;
     private String pagamentoCompraIar;
     private Set compraProdutoIars = new HashSet(0);

    public CompraIar() {
    }

	
    public CompraIar(int idCompraIar, FornecedorZht fornecedorZht, FuncionarioIar funcionarioIar, Date dataIar, double valorIar, String pagamentoCompraIar) {
        this.idCompraIar = idCompraIar;
        this.fornecedorZht = fornecedorZht;
        this.funcionarioIar = funcionarioIar;
        this.dataIar = dataIar;
        this.valorIar = valorIar;
        this.pagamentoCompraIar = pagamentoCompraIar;
    }
    public CompraIar(int idCompraIar, FornecedorZht fornecedorZht, FuncionarioIar funcionarioIar, Date dataIar, double valorIar, String pagamentoCompraIar, Set compraProdutoIars) {
       this.idCompraIar = idCompraIar;
       this.fornecedorZht = fornecedorZht;
       this.funcionarioIar = funcionarioIar;
       this.dataIar = dataIar;
       this.valorIar = valorIar;
       this.pagamentoCompraIar = pagamentoCompraIar;
       this.compraProdutoIars = compraProdutoIars;
    }
   
     @Id 

    
    @Column(name="id_compra_iar", unique=true, nullable=false)
    public int getIdCompraIar() {
        return this.idCompraIar;
    }
    
    public void setIdCompraIar(int idCompraIar) {
        this.idCompraIar = idCompraIar;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_fornecedor_zht", nullable=false)
    public FornecedorZht getFornecedorZht() {
        return this.fornecedorZht;
    }
    
    public void setFornecedorZht(FornecedorZht fornecedorZht) {
        this.fornecedorZht = fornecedorZht;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_funcionario_iar", nullable=false)
    public FuncionarioIar getFuncionarioIar() {
        return this.funcionarioIar;
    }
    
    public void setFuncionarioIar(FuncionarioIar funcionarioIar) {
        this.funcionarioIar = funcionarioIar;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_iar", nullable=false, length=19)
    public Date getDataIar() {
        return this.dataIar;
    }
    
    public void setDataIar(Date dataIar) {
        this.dataIar = dataIar;
    }

    
    @Column(name="valor_iar", nullable=false, precision=7)
    public double getValorIar() {
        return this.valorIar;
    }
    
    public void setValorIar(double valorIar) {
        this.valorIar = valorIar;
    }

    
    @Column(name="pagamento_compra_iar", nullable=false, length=45)
    public String getPagamentoCompraIar() {
        return this.pagamentoCompraIar;
    }
    
    public void setPagamentoCompraIar(String pagamentoCompraIar) {
        this.pagamentoCompraIar = pagamentoCompraIar;
    }




}


