package bean;
// Generated 13/12/2024 19:27:56 by Hibernate Tools 4.3.1



import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FornecedorZht generated by hbm2java
 */
@Entity
@Table(name="fornecedor_zht"
    ,catalog="db_zahraa_tormos"
)
public class FornecedorZht  implements java.io.Serializable {


     private int idfornecedorZht;
     private String nomeZht;
     private String cnpjZht;
     private String emailZht;
     private String cepZht;
     private String enderecoZht;
     private String cidadeZht;
     private String estadoZht;
     private String nomeFuncionarioZht;
     private String bairroZht;
     private String ruaZht;
     private String complementoZht;
     private String contatoZht;
     private String paisZht;
     private String dddZht;


    public FornecedorZht() {
    }

	
    public FornecedorZht(String nomeZht, String cnpjZht, String emailZht, String cepZht, String enderecoZht, String cidadeZht, String estadoZht, String nomeFuncionarioZht, String bairroZht, String ruaZht, String complementoZht, String contatoZht, String paisZht, String dddZht) {
        this.nomeZht = nomeZht;
        this.cnpjZht = cnpjZht;
        this.emailZht = emailZht;
        this.cepZht = cepZht;
        this.enderecoZht = enderecoZht;
        this.cidadeZht = cidadeZht;
        this.estadoZht = estadoZht;
        this.nomeFuncionarioZht = nomeFuncionarioZht;
        this.bairroZht = bairroZht;
        this.ruaZht = ruaZht;
        this.complementoZht = complementoZht;
        this.contatoZht = contatoZht;
        this.paisZht = paisZht;
        this.dddZht = dddZht;
    }
    public FornecedorZht(String nomeZht, String cnpjZht, String emailZht, String cepZht, String enderecoZht, String cidadeZht, String estadoZht, String nomeFuncionarioZht, String bairroZht, String ruaZht, String complementoZht, String contatoZht, String paisZht, String dddZht, Set compraFornecedorIars, Set produtoZhts) {
       this.nomeZht = nomeZht;
       this.cnpjZht = cnpjZht;
       this.emailZht = emailZht;
       this.cepZht = cepZht;
       this.enderecoZht = enderecoZht;
       this.cidadeZht = cidadeZht;
       this.estadoZht = estadoZht;
       this.nomeFuncionarioZht = nomeFuncionarioZht;
       this.bairroZht = bairroZht;
       this.ruaZht = ruaZht;
       this.complementoZht = complementoZht;
       this.contatoZht = contatoZht;
       this.paisZht = paisZht;
       this.dddZht = dddZht;
     
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idfornecedor_zht", unique=true, nullable=false)
    public int getIdfornecedorZht() {
        return this.idfornecedorZht;
    }
    
    public void setIdfornecedorZht(int idfornecedorZht) {
        this.idfornecedorZht = idfornecedorZht;
    }

    
    @Column(name="nome_zht", nullable=false, length=70)
    public String getNomeZht() {
        return this.nomeZht;
    }
    
    public void setNomeZht(String nomeZht) {
        this.nomeZht = nomeZht;
    }

    
    @Column(name="cnpj_zht", nullable=false, length=14)
    public String getCnpjZht() {
        return this.cnpjZht;
    }
    
    public void setCnpjZht(String cnpjZht) {
        this.cnpjZht = cnpjZht;
    }

    
    @Column(name="email_zht", nullable=false, length=50)
    public String getEmailZht() {
        return this.emailZht;
    }
    
    public void setEmailZht(String emailZht) {
        this.emailZht = emailZht;
    }

    
    @Column(name="cep_zht", nullable=false, length=8)
    public String getCepZht() {
        return this.cepZht;
    }
    
    public void setCepZht(String cepZht) {
        this.cepZht = cepZht;
    }

    
    @Column(name="endereco_zht", nullable=false, length=160)
    public String getEnderecoZht() {
        return this.enderecoZht;
    }
    
    public void setEnderecoZht(String enderecoZht) {
        this.enderecoZht = enderecoZht;
    }

    
    @Column(name="cidade_zht", nullable=false, length=45)
    public String getCidadeZht() {
        return this.cidadeZht;
    }
    
    public void setCidadeZht(String cidadeZht) {
        this.cidadeZht = cidadeZht;
    }

    
    @Column(name="estado_zht", nullable=false, length=2)
    public String getEstadoZht() {
        return this.estadoZht;
    }
    
    public void setEstadoZht(String estadoZht) {
        this.estadoZht = estadoZht;
    }

    
    @Column(name="nome_funcionario_zht", nullable=false, length=80)
    public String getNomeFuncionarioZht() {
        return this.nomeFuncionarioZht;
    }
    
    public void setNomeFuncionarioZht(String nomeFuncionarioZht) {
        this.nomeFuncionarioZht = nomeFuncionarioZht;
    }

    
    @Column(name="bairro_zht", nullable=false, length=30)
    public String getBairroZht() {
        return this.bairroZht;
    }
    
    public void setBairroZht(String bairroZht) {
        this.bairroZht = bairroZht;
    }

    
    @Column(name="rua_zht", nullable=false, length=30)
    public String getRuaZht() {
        return this.ruaZht;
    }
    
    public void setRuaZht(String ruaZht) {
        this.ruaZht = ruaZht;
    }

    
    @Column(name="complemento_zht", nullable=false, length=45)
    public String getComplementoZht() {
        return this.complementoZht;
    }
    
    public void setComplementoZht(String complementoZht) {
        this.complementoZht = complementoZht;
    }

    
    @Column(name="contato_zht", nullable=false, length=45)
    public String getContatoZht() {
        return this.contatoZht;
    }
    
    public void setContatoZht(String contatoZht) {
        this.contatoZht = contatoZht;
    }

    
    @Column(name="pais_zht", nullable=false, length=30)
    public String getPaisZht() {
        return this.paisZht;
    }
    
    public void setPaisZht(String paisZht) {
        this.paisZht = paisZht;
    }

    
    @Column(name="ddd_zht", nullable=false, length=5)
    public String getDddZht() {
        return this.dddZht;
    }
    
    public void setDddZht(String dddZht) {
        this.dddZht = dddZht;
    }





}


