package bean;
// Generated 13/12/2024 19:27:56 by Hibernate Tools 4.3.1


import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FuncionarioIar generated by hbm2java
 */
@Entity
@Table(name="funcionario_iar"
    ,catalog="db_zahraa_tormos"
)
public class FuncionarioIar  implements java.io.Serializable {


     private int idFuncionarioIar;
     private String nomeFuncionarioIar;
     private String ruaFuncionarioIar;
     private String bairroFuncionarioIar;
     private String estadoFuncionarioIar;
     private String complementoFuncionarioIar;
     private int numCasaFuncionarioIar;
     private String funcaoFuncionarioIar;

    public FuncionarioIar() {
    }

	
    public FuncionarioIar(String nomeFuncionarioIar, String ruaFuncionarioIar, String bairroFuncionarioIar, String estadoFuncionarioIar, String complementoFuncionarioIar, int numCasaFuncionarioIar, String funcaoFuncionarioIar) {
        this.nomeFuncionarioIar = nomeFuncionarioIar;
        this.ruaFuncionarioIar = ruaFuncionarioIar;
        this.bairroFuncionarioIar = bairroFuncionarioIar;
        this.estadoFuncionarioIar = estadoFuncionarioIar;
        this.complementoFuncionarioIar = complementoFuncionarioIar;
        this.numCasaFuncionarioIar = numCasaFuncionarioIar;
        this.funcaoFuncionarioIar = funcaoFuncionarioIar;
    }
    public FuncionarioIar(String nomeFuncionarioIar, String ruaFuncionarioIar, String bairroFuncionarioIar, String estadoFuncionarioIar, String complementoFuncionarioIar, int numCasaFuncionarioIar, String funcaoFuncionarioIar, Set compraIars, Set vendasZhts) {
       this.nomeFuncionarioIar = nomeFuncionarioIar;
       this.ruaFuncionarioIar = ruaFuncionarioIar;
       this.bairroFuncionarioIar = bairroFuncionarioIar;
       this.estadoFuncionarioIar = estadoFuncionarioIar;
       this.complementoFuncionarioIar = complementoFuncionarioIar;
       this.numCasaFuncionarioIar = numCasaFuncionarioIar;
       this.funcaoFuncionarioIar = funcaoFuncionarioIar;
     
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_funcionario_iar", unique=true, nullable=false)
    public int getIdFuncionarioIar() {
        return this.idFuncionarioIar;
    }
    
    public void setIdFuncionarioIar(int idFuncionarioIar) {
        this.idFuncionarioIar = idFuncionarioIar;
    }

    
    @Column(name="nome_funcionario_iar", nullable=false, length=50)
    public String getNomeFuncionarioIar() {
        return this.nomeFuncionarioIar;
    }
    
    public void setNomeFuncionarioIar(String nomeFuncionarioIar) {
        this.nomeFuncionarioIar = nomeFuncionarioIar;
    }

    
    @Column(name="rua_funcionario_iar", nullable=false, length=45)
    public String getRuaFuncionarioIar() {
        return this.ruaFuncionarioIar;
    }
    
    public void setRuaFuncionarioIar(String ruaFuncionarioIar) {
        this.ruaFuncionarioIar = ruaFuncionarioIar;
    }

    
    @Column(name="bairro_funcionario_iar", nullable=false, length=50)
    public String getBairroFuncionarioIar() {
        return this.bairroFuncionarioIar;
    }
    
    public void setBairroFuncionarioIar(String bairroFuncionarioIar) {
        this.bairroFuncionarioIar = bairroFuncionarioIar;
    }

    
    @Column(name="estado_funcionario_iar", nullable=false, length=2)
    public String getEstadoFuncionarioIar() {
        return this.estadoFuncionarioIar;
    }
    
    public void setEstadoFuncionarioIar(String estadoFuncionarioIar) {
        this.estadoFuncionarioIar = estadoFuncionarioIar;
    }

    
    @Column(name="complemento_funcionario_iar", nullable=false, length=70)
    public String getComplementoFuncionarioIar() {
        return this.complementoFuncionarioIar;
    }
    
    public void setComplementoFuncionarioIar(String complementoFuncionarioIar) {
        this.complementoFuncionarioIar = complementoFuncionarioIar;
    }

    
    @Column(name="num_casa_funcionario_iar", nullable=false)
    public int getNumCasaFuncionarioIar() {
        return this.numCasaFuncionarioIar;
    }
    
    public void setNumCasaFuncionarioIar(int numCasaFuncionarioIar) {
        this.numCasaFuncionarioIar = numCasaFuncionarioIar;
    }

    
    @Column(name="funcao_funcionario_iar", nullable=false, length=45)
    public String getFuncaoFuncionarioIar() {
        return this.funcaoFuncionarioIar;
    }
    
    public void setFuncaoFuncionarioIar(String funcaoFuncionarioIar) {
        this.funcaoFuncionarioIar = funcaoFuncionarioIar;
    }
    
    
    @Override
    public String toString() {
        return this.idFuncionarioIar + " - " + this.nomeFuncionarioIar;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof ClienteIar) {
            FuncionarioIar funcionario = (FuncionarioIar) object;
            if (funcionario.getIdFuncionarioIar() == this.getIdFuncionarioIar()) {
                return true;
            }
        }
        return false;
    }





}


