package bean;
// Generated 13/12/2024 19:27:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdutoVendasZhtId generated by hbm2java
 */
@Embeddable
public class ProdutoVendasZhtId  implements java.io.Serializable {


     private byte fkProdutoZht;
     private byte fkVendasZht;

    public ProdutoVendasZhtId() {
    }

    public ProdutoVendasZhtId(byte fkProdutoZht, byte fkVendasZht) {
       this.fkProdutoZht = fkProdutoZht;
       this.fkVendasZht = fkVendasZht;
    }
   


    @Column(name="fk_produto_zht", nullable=false)
    public byte getFkProdutoZht() {
        return this.fkProdutoZht;
    }
    
    public void setFkProdutoZht(byte fkProdutoZht) {
        this.fkProdutoZht = fkProdutoZht;
    }


    @Column(name="fk_vendas_zht", nullable=false)
    public byte getFkVendasZht() {
        return this.fkVendasZht;
    }
    
    public void setFkVendasZht(byte fkVendasZht) {
        this.fkVendasZht = fkVendasZht;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoVendasZhtId) ) return false;
		 ProdutoVendasZhtId castOther = ( ProdutoVendasZhtId ) other; 
         
		 return (this.getFkProdutoZht()==castOther.getFkProdutoZht())
 && (this.getFkVendasZht()==castOther.getFkVendasZht());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFkProdutoZht();
         result = 37 * result + this.getFkVendasZht();
         return result;
   }   


}


