package bean;
// Generated 13/12/2024 19:27:56 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProdutoVendasZht generated by hbm2java
 */
@Entity
@Table(name="produto_vendas_zht"
    ,catalog="db_zahraa_tormos"
)
public class ProdutoVendasZht  implements java.io.Serializable {


     private ProdutoVendasZhtId id;
     private int quantidadeZht;

    public ProdutoVendasZht() {
    }

    public ProdutoVendasZht(ProdutoVendasZhtId id, int quantidadeZht) {
       this.id = id;
       this.quantidadeZht = quantidadeZht;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fkProdutoZht", column=@Column(name="fk_produto_zht", nullable=false) ), 
        @AttributeOverride(name="fkVendasZht", column=@Column(name="fk_vendas_zht", nullable=false) ) } )
    public ProdutoVendasZhtId getId() {
        return this.id;
    }
    
    public void setId(ProdutoVendasZhtId id) {
        this.id = id;
    }

    
    @Column(name="quantidade_zht", nullable=false)
    public int getQuantidadeZht() {
        return this.quantidadeZht;
    }
    
    public void setQuantidadeZht(int quantidadeZht) {
        this.quantidadeZht = quantidadeZht;
    }




}


