package bean;
// Generated 06/02/2025 17:20:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PromocoesZht generated by hbm2java
 */
@Entity
@Table(name="promocoes_zht"
    ,catalog="db_zahraa_tormos"
)
public class PromocoesZht  implements java.io.Serializable {


     private int idpromocoesZht;
     private String nomeZht;
     private Date dataInicioZht;
     private Date dataTerminoZht;
     private String tipoZht;
     private int descontoZht;
     private int statusZht;
     private String descricaoZht;

    public PromocoesZht() {
    }

	
    public PromocoesZht(int idpromocoesZht, String nomeZht, String tipoZht, int descontoZht, int statusZht, String descricaoZht) {
        this.idpromocoesZht = idpromocoesZht;
        this.nomeZht = nomeZht;
        this.tipoZht = tipoZht;
        this.descontoZht = descontoZht;
        this.statusZht = statusZht;
        this.descricaoZht = descricaoZht;
    }
    public PromocoesZht(int idpromocoesZht, String nomeZht, Date dataInicioZht, Date dataTerminoZht, String tipoZht, int descontoZht, int statusZht, String descricaoZht) {
       this.idpromocoesZht = idpromocoesZht;
       this.nomeZht = nomeZht;
       this.dataInicioZht = dataInicioZht;
       this.dataTerminoZht = dataTerminoZht;
       this.tipoZht = tipoZht;
       this.descontoZht = descontoZht;
       this.statusZht = statusZht;
       this.descricaoZht = descricaoZht;
    }
   
     @Id 

    
    @Column(name="idpromocoes_zht", unique=true, nullable=false)
    public int getIdpromocoesZht() {
        return this.idpromocoesZht;
    }
    
    public void setIdpromocoesZht(int idpromocoesZht) {
        this.idpromocoesZht = idpromocoesZht;
    }

    
    @Column(name="nome_zht", nullable=false, length=45)
    public String getNomeZht() {
        return this.nomeZht;
    }
    
    public void setNomeZht(String nomeZht) {
        this.nomeZht = nomeZht;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_inicio_zht", length=10)
    public Date getDataInicioZht() {
        return this.dataInicioZht;
    }
    
    public void setDataInicioZht(Date dataInicioZht) {
        this.dataInicioZht = dataInicioZht;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_termino_zht", length=10)
    public Date getDataTerminoZht() {
        return this.dataTerminoZht;
    }
    
    public void setDataTerminoZht(Date dataTerminoZht) {
        this.dataTerminoZht = dataTerminoZht;
    }

    
    @Column(name="tipo_zht", nullable=false, length=45)
    public String getTipoZht() {
        return this.tipoZht;
    }
    
    public void setTipoZht(String tipoZht) {
        this.tipoZht = tipoZht;
    }

    
    @Column(name="desconto_zht", nullable=false)
    public int getDescontoZht() {
        return this.descontoZht;
    }
    
    public void setDescontoZht(int descontoZht) {
        this.descontoZht = descontoZht;
    }

    
    @Column(name="status_zht", nullable=false)
    public int getStatusZht() {
        return this.statusZht;
    }
    
    public void setStatusZht(int statusZht) {
        this.statusZht = statusZht;
    }

    
    @Column(name="descricao_zht", nullable=false, length=70)
    public String getDescricaoZht() {
        return this.descricaoZht;
    }
    
    public void setDescricaoZht(String descricaoZht) {
        this.descricaoZht = descricaoZht;
    }




}


