package bean;
// Generated 06/02/2025 17:20:47 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosIar generated by hbm2java
 */
@Entity
@Table(name="usuarios_iar"
    ,catalog="db_zahraa_tormos"
)
public class UsuariosIar  implements java.io.Serializable {


     private int idUsuariosIar;
     private String nomeUsuarioIar;
     private String apelidoIar;
     private String cpfIar;
     private Date dataNascimentoIar;
     private String senhaIar;
     private String nivelIar;
     private String ativoIar;

    public UsuariosIar() {
    }

	
    public UsuariosIar(int idUsuariosIar, String nomeUsuarioIar, String apelidoIar, String cpfIar, String senhaIar, String nivelIar, String ativoIar) {
        this.idUsuariosIar = idUsuariosIar;
        this.nomeUsuarioIar = nomeUsuarioIar;
        this.apelidoIar = apelidoIar;
        this.cpfIar = cpfIar;
        this.senhaIar = senhaIar;
        this.nivelIar = nivelIar;
        this.ativoIar = ativoIar;
    }
    public UsuariosIar(int idUsuariosIar, String nomeUsuarioIar, String apelidoIar, String cpfIar, Date dataNascimentoIar, String senhaIar, String nivelIar, String ativoIar) {
       this.idUsuariosIar = idUsuariosIar;
       this.nomeUsuarioIar = nomeUsuarioIar;
       this.apelidoIar = apelidoIar;
       this.cpfIar = cpfIar;
       this.dataNascimentoIar = dataNascimentoIar;
       this.senhaIar = senhaIar;
       this.nivelIar = nivelIar;
       this.ativoIar = ativoIar;
    }
   
     @Id 

    
    @Column(name="id_usuarios_iar", unique=true, nullable=false)
    public int getIdUsuariosIar() {
        return this.idUsuariosIar;
    }
    
    public void setIdUsuariosIar(int idUsuariosIar) {
        this.idUsuariosIar = idUsuariosIar;
    }

    
    @Column(name="nome_usuario_iar", nullable=false, length=50)
    public String getNomeUsuarioIar() {
        return this.nomeUsuarioIar;
    }
    
    public void setNomeUsuarioIar(String nomeUsuarioIar) {
        this.nomeUsuarioIar = nomeUsuarioIar;
    }

    
    @Column(name="apelido_iar", nullable=false, length=45)
    public String getApelidoIar() {
        return this.apelidoIar;
    }
    
    public void setApelidoIar(String apelidoIar) {
        this.apelidoIar = apelidoIar;
    }

    
    @Column(name="cpf_iar", nullable=false, length=15)
    public String getCpfIar() {
        return this.cpfIar;
    }
    
    public void setCpfIar(String cpfIar) {
        this.cpfIar = cpfIar;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_iar", length=10)
    public Date getDataNascimentoIar() {
        return this.dataNascimentoIar;
    }
    
    public void setDataNascimentoIar(Date dataNascimentoIar) {
        this.dataNascimentoIar = dataNascimentoIar;
    }

    
    @Column(name="senha_iar", nullable=false, length=80)
    public String getSenhaIar() {
        return this.senhaIar;
    }
    
    public void setSenhaIar(String senhaIar) {
        this.senhaIar = senhaIar;
    }

    
    @Column(name="nivel_iar", nullable=false, length=10)
    public String getNivelIar() {
        return this.nivelIar;
    }
    
    public void setNivelIar(String nivelIar) {
        this.nivelIar = nivelIar;
    }

    
    @Column(name="ativo_iar", nullable=false, length=1)
    public String getAtivoIar() {
        return this.ativoIar;
    }
    
    public void setAtivoIar(String ativoIar) {
        this.ativoIar = ativoIar;
    }




}


