package bean;
// Generated 13/12/2024 19:27:56 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasClientesZht generated by hbm2java
 */
@Entity
@Table(name="vendas_clientes_zht"
    ,catalog="db_zahraa_tormos"
)
public class VendasClientesZht  implements java.io.Serializable {


     private VendasClientesZhtId id;
     private ClienteIar clienteIar;
     private VendasZht vendasZht;
     private int quantidadeZht;

    public VendasClientesZht() {
    }

    public VendasClientesZht(VendasClientesZhtId id, ClienteIar clienteIar, VendasZht vendasZht, int quantidadeZht) {
       this.id = id;
       this.clienteIar = clienteIar;
       this.vendasZht = vendasZht;
       this.quantidadeZht = quantidadeZht;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vendasZht", column=@Column(name="vendas_zht", nullable=false) ), 
        @AttributeOverride(name="clienteZht", column=@Column(name="cliente_zht", nullable=false) ) } )
    public VendasClientesZhtId getId() {
        return this.id;
    }
    
    public void setId(VendasClientesZhtId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_zht", nullable=false, insertable=false, updatable=false)
    public ClienteIar getClienteIar() {
        return this.clienteIar;
    }
    
    public void setClienteIar(ClienteIar clienteIar) {
        this.clienteIar = clienteIar;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendas_zht", nullable=false, insertable=false, updatable=false)
    public VendasZht getVendasZht() {
        return this.vendasZht;
    }
    
    public void setVendasZht(VendasZht vendasZht) {
        this.vendasZht = vendasZht;
    }

    
    @Column(name="quantidade_zht", nullable=false)
    public int getQuantidadeZht() {
        return this.quantidadeZht;
    }
    
    public void setQuantidadeZht(int quantidadeZht) {
        this.quantidadeZht = quantidadeZht;
    }




}


