package bean;
// Generated 06/02/2025 17:20:47 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasProdutoZht generated by hbm2java
 */
@Entity
@Table(name="vendas_produto_zht"
    ,catalog="db_zahraa_tormos"
)
public class VendasProdutoZht  implements java.io.Serializable {


     private int idVendaProdutoZht;
     private ProdutoZht produtoZht;
     private VendasZht vendasZht;
     private int quantidadeZht;
     private double valorUnitarioZht;

    public VendasProdutoZht() {
    }

    public VendasProdutoZht(int idVendaProdutoZht, ProdutoZht produtoZht, VendasZht vendasZht, int quantidadeZht, double valorUnitarioZht) {
       this.idVendaProdutoZht = idVendaProdutoZht;
       this.produtoZht = produtoZht;
       this.vendasZht = vendasZht;
       this.quantidadeZht = quantidadeZht;
       this.valorUnitarioZht = valorUnitarioZht;
    }
   
     @Id 

    
    @Column(name="id_venda_produto_zht", unique=true, nullable=false)
    public int getIdVendaProdutoZht() {
        return this.idVendaProdutoZht;
    }
    
    public void setIdVendaProdutoZht(int idVendaProdutoZht) {
        this.idVendaProdutoZht = idVendaProdutoZht;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produto_zht_id_produto_zht", nullable=false)
    public ProdutoZht getProdutoZht() {
        return this.produtoZht;
    }
    
    public void setProdutoZht(ProdutoZht produtoZht) {
        this.produtoZht = produtoZht;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vendas_zht_id_vendas_zht", nullable=false)
    public VendasZht getVendasZht() {
        return this.vendasZht;
    }
    
    public void setVendasZht(VendasZht vendasZht) {
        this.vendasZht = vendasZht;
    }

    
    @Column(name="quantidade_zht", nullable=false)
    public int getQuantidadeZht() {
        return this.quantidadeZht;
    }
    
    public void setQuantidadeZht(int quantidadeZht) {
        this.quantidadeZht = quantidadeZht;
    }

    
    @Column(name="valor_unitario_zht", nullable=false, precision=7)
    public double getValorUnitarioZht() {
        return this.valorUnitarioZht;
    }
    
    public void setValorUnitarioZht(double valorUnitarioZht) {
        this.valorUnitarioZht = valorUnitarioZht;
    }




}


