package bean;
// Generated 13/12/2024 19:27:56 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasZht generated by hbm2java
 */
@Entity
@Table(name="vendas_zht"
    ,catalog="db_zahraa_tormos"
)
public class VendasZht  implements java.io.Serializable {


     private int idVendasZht;
     private ClienteIar clienteIar;
     private FuncionarioIar funcionarioIar;
     private int quantidadeVendaZht;
     private double valorVendaZht;
     private Date dataVendaZht;
     private String pagamentoVendaZht;

    public VendasZht() {
    }

	
    public VendasZht(int idVendasZht, ClienteIar clienteIar, FuncionarioIar funcionarioIar, int quantidadeVendaZht, double valorVendaZht, Date dataVendaZht, String pagamentoVendaZht) {
        this.idVendasZht = idVendasZht;
        this.clienteIar = clienteIar;
        this.funcionarioIar = funcionarioIar;
        this.quantidadeVendaZht = quantidadeVendaZht;
        this.valorVendaZht = valorVendaZht;
        this.dataVendaZht = dataVendaZht;
        this.pagamentoVendaZht = pagamentoVendaZht;
    }
   
     @Id 

    
    @Column(name="id_vendas_zht", unique=true, nullable=false)
    public int getIdVendasZht() {
        return this.idVendasZht;
    }
    
    public void setIdVendasZht(int idVendasZht) {
        this.idVendasZht = idVendasZht;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_cliente_iar", nullable=false)
    public ClienteIar getClienteIar() {
        return this.clienteIar;
    }
    
    public void setClienteIar(ClienteIar clienteIar) {
        this.clienteIar = clienteIar;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_funcionario_iar", nullable=false)
    public FuncionarioIar getFuncionarioIar() {
        return this.funcionarioIar;
    }
    
    public void setFuncionarioIar(FuncionarioIar funcionarioIar) {
        this.funcionarioIar = funcionarioIar;
    }

    
    @Column(name="quantidade_venda_zht", nullable=false)
    public int getQuantidadeVendaZht() {
        return this.quantidadeVendaZht;
    }
    
    public void setQuantidadeVendaZht(int quantidadeVendaZht) {
        this.quantidadeVendaZht = quantidadeVendaZht;
    }

    
    @Column(name="valor_venda_zht", nullable=false, precision=7)
    public double getValorVendaZht() {
        return this.valorVendaZht;
    }
    
    public void setValorVendaZht(double valorVendaZht) {
        this.valorVendaZht = valorVendaZht;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_venda_zht", nullable=false, length=19)
    public Date getDataVendaZht() {
        return this.dataVendaZht;
    }
    
    public void setDataVendaZht(Date dataVendaZht) {
        this.dataVendaZht = dataVendaZht;
    }

    
    @Column(name="pagamento_venda_zht", nullable=false, length=45)
    public String getPagamentoVendaZht() {
        return this.pagamentoVendaZht;
    }
    
    public void setPagamentoVendaZht(String pagamentoVendaZht) {
        this.pagamentoVendaZht = pagamentoVendaZht;
    }



}


