package bean;
// Generated 13/12/2024 19:27:56 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VendasClientesZhtId generated by hbm2java
 */
@Embeddable
public class VendasClientesZhtId  implements java.io.Serializable {


     private int vendasZht;
     private int clienteZht;

    public VendasClientesZhtId() {
    }

    public VendasClientesZhtId(int vendasZht, int clienteZht) {
       this.vendasZht = vendasZht;
       this.clienteZht = clienteZht;
    }
   


    @Column(name="vendas_zht", nullable=false)
    public int getVendasZht() {
        return this.vendasZht;
    }
    
    public void setVendasZht(int vendasZht) {
        this.vendasZht = vendasZht;
    }


    @Column(name="cliente_zht", nullable=false)
    public int getClienteZht() {
        return this.clienteZht;
    }
    
    public void setClienteZht(int clienteZht) {
        this.clienteZht = clienteZht;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VendasClientesZhtId) ) return false;
		 VendasClientesZhtId castOther = ( VendasClientesZhtId ) other; 
         
		 return (this.getVendasZht()==castOther.getVendasZht())
 && (this.getClienteZht()==castOther.getClienteZht());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVendasZht();
         result = 37 * result + this.getClienteZht();
         return result;
   }   


}


